### ISSUE TITLE
GWR data model has changed and now breaks the app

### ISSUE THREAD

**Issue by AFoletti** [sonnendach/sonnendach-ui#188]
**Situation:**
With the [last API release](https://api3.geo.admin.ch/releasenotes/index.html#release-20201028-wednesday-october-28th-2020), the GWD data model has changed (see [this commit](https://github.com/geoadmin/mf-chsdi3/commit/ea3276bf3140199a33457f45e611325117ceef3c#diff-e4296133710fa3c2f02d7059e857dcf9501379ca09f3b730cead7b91d6191f03) and [documentation here](https://www.bfs.admin.ch/bfs/en/home/statistics/catalogues-databases/publications.assetdetail.7008785.html) ).
The change was [announced in July](https://api3.geo.admin.ch/releasenotes/index.html#release-20200701-wednesday-july-1st-2020).

Since the data model has changed, the sonnendach.ch application does not work as intended anymore.

**Steps to reproduce:**
- open sonnendach.ch
- search for and select an address
- once you get the results (which are correct since I guess coming from the geoadmin search service!), click on one roof in the map

**Result:**
- the new surface is selected with its data, but the address information is missing since it comes from an identify (whose model has changed)
![image](https://user-images.githubusercontent.com/691243/97971282-17335380-1dc3-11eb-801c-5acd39ccdc43.png)

**Expected result:**
- the address information is correctly displayed

**Comment by AFoletti** [comment]
@cype 
Problem found.
[This line](https://github.com/SFOE/sonnendach-ui/blob/bcfb8f90c81019e90b7d361eb05ec16b57e0cad5/assets/js/init.js#L20) and the following one should be:

`label = attr.strname_deinr +
          ' <br>' + attr.dplz4 + ' ' + attr.dplzname;`

I don't know how to test, but it should in my opinion do the trick 😄

**Comment by AFoletti** [comment]
The proposed solution works.

Fixed in prod. Thanks Nico!

**Comment by cype** [comment]
Re-opened -> integrate Code in next Deploy
