### ISSUE TITLE
Requests to get best roof of a building

### ISSUE THREAD

**Issue by gjn** [sonnendach/sonnendach-ui#4]
As discussed this morning, a requirement is to get the best roof for a building when doing an identify request (which is either triggered by search or by geolocation. This is not supported out of the box because the datamodel is roofs. Anyhow, roofs have a building id which is the same. So the approach is to do a standard identify request and a second request to get all roofs for this building.

[Identify request (simulating a requestion on the map)](http://mf-chsdi3.dev.bgdi.ch/ltfoa_solarenergie_daecher/rest/services/ech/MapServer/identify?geometry=637842.5,196398.25&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1920,765,96&layers=all:ch.bfe.solarenergie-eignung-daecher&mapExtent=637354.6684856485,196298.04718398678,638314.6684856485,196680.54718398678&tolerance=10)

In the results of the requests above will be 1 or more roof parts. To get each roof for a given building, the find service is used to get all roof parts of a given building, using the `building_id` parameter of the previous request. 

[Corresponding find request](http://mf-chsdi3.dev.bgdi.ch/ltfoa_solarenergie_daecher/rest/services/api/MapServer/find?layer=ch.bfe.solarenergie-eignung-daecher&searchText=679e0785-62c1-4f22-9367-10b4316c5347&searchField=building_id)

With the second requestion, you will be able to determine the 'best roof' client side and displaying the corresponding values to the user.

**Comment by cype** [comment]
The 'best roof' is the roof with the highest value in the attribute MSTRAHLUNG
