### ISSUE TITLE
PDF Export or HTML Print

### ISSUE THREAD

**Issue by gjn** [sonnendach/sonnendach-ui#6]
In a first version, all information will be printed out directly from a html page. We propose to use a api3 standard extended tooltip (including map to show object) for this functionality - optimized with print in mind.

The extended tooltip will not appear in map.geo.admin.ch in the tooltip. In the tooltip, the link will be to sonnendach.ch. On sonnendach.ch, there will be a link back to the api3 extended tooltip.

**Comment by cype** [comment]
Take an existing extended tooltip as template and fill with same method as in init.js

**Comment by cype** [comment]
don't forget: Denkmalschutz-Info pro Kanton
