### ISSUE TITLE
CSS problems

### ISSUE THREAD

**Issue by cype** [sonnendach/sonnendach-ui#73]
Magnifier-symbol Search-Input-Field: on IE and Firebox the symbol is not inside field

iPhone: Buttons "Eignung" and "Solarstrom für X Franken"  in the map-section are too small on an iPhone-screen.

Roof found but no address found -> wrong titles are shown, for ex see http://www.energiestadtfinder.ch/sonnendach/index.html?featureId=89646

**Comment by gjn** [comment]
@cype Can you add @pfanguin as editor to this project?

**Comment by cype** [comment]
done. Welcome @pfanguin

**Comment by pfanguin** [comment]
Thanks

**Comment by cype** [comment]
also:
Bund-logo should be horizontally in line with text "bundesamt für..."
